name: Deploy to Google Cloud Functions

on:
  push:
    branches:
      - main  # Trigger deployment on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Java (Java 21 for your project)
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'

    # Step 3: Set up Google Cloud SDK
    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_KEY }}
        export_default_credentials: true

    # Step 4: Authenticate Google Cloud
    - name: Authenticate with Google Cloud
      run: gcloud auth activate-service-account --key-file="${{ secrets.GCP_KEY }}"
    
    # Step 5: Build the project with Maven
    - name: Build with Maven
      run: mvn clean package

    # Step 6: Deploy to Google Cloud Functions
    - name: Deploy to Google Cloud Functions
      run: |
        gcloud functions deploy getFromBunnyFunction \
          --entry-point=com.gcfv2.GetFromBunny \
          --runtime=java21 \
          --trigger-http \
          --allow-unauthenticated \
          --source=.
