name: Deploy Google Cloud Function

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allows for manual triggers

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Google Cloud SDK
    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_KEY }}
        export_default_credentials: true

    - name: Authenticate Google Cloud
      run: |
        echo "${{ secrets.GCP_KEY }}" > gcp-key.json
        gcloud auth activate-service-account --key-file=gcp-key.json
        
    - name: Set up Maven
      run: |
        sudo apt-get update
        sudo apt-get install maven


    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Check Java version
      run: java -version

    # Step 3: Build the project
    - name: Build with Maven
      run: mvn clean package

    # Step 4: Deploy to Google Cloud Functions
    - name: Deploy to Cloud Function
      run: |
        gcloud functions deploy getFromBunnyFunction \
          --entry-point=com.gcfv2.GetFromBunny \
          --runtime=java21 \
          --trigger-http \
          --allow-unauthenticated \
          --source=.
