name: Deploy Google Cloud Function

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allows for manual triggers

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Authenticate using Workload Identity Federation
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
        service_account: ${{ secrets.SERVICE_ACCOUNT_EMAIL }}

    # Step 3: Set up Google Cloud SDK
    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    # Step 4: Set up Java JDK
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Check Java version
      run: java -version

    # Step 5: Set up Maven
    - name: Set up Maven
      run: |
        sudo apt-get update
        sudo apt-get install -y maven

    # Step 6: Build the project
    - name: Build with Maven
      run: mvn clean package

    # Step 7: Deploy to Google Cloud Functions
    - name: Deploy to Cloud Function
      run: |
        gcloud functions deploy getFromBunnyFunction \
          --entry-point=com.gcfv2.GetFromBunny \
          --runtime=java21 \
          --trigger-http \
          --allow-unauthenticated \
          --source=.
